### PR TITLE
Update Copyright Year to 2017

### PR DESCRIPTION
**Pull request by hchasey**
From 2016 to 2017.

### CODE REVIEW

**Review by benhutton — APPROVED** [review]

**Comment by hchasey** [comment]
@benhutton – let me know if you have tips on the test failures. Also, I don't think we need to cut a new release for the copyright update, but I guess with `develop` and Gitflow, I can still just merge this once tests pass? Thanks!

**Comment by benhutton** [comment]
@hchasey something is wrong with how github and circle are connected on this repo. I don't have the right level of authorization on either of them to fix it. @gaganawhad want to take a look?

**Comment by gaganawhad** [comment]
yeah, I'll take a look here

**Comment by gaganawhad** [comment]
@benhutton there is a different error here now. It probably required one org member to follow this project. We might have to update the dependencies.

**Comment by benhutton** [comment]
@hchasey can you rebase against the latest `develop` branch?

**Pull request closed without merging**
